name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install
      - name: Install Playwright
        run: npx playwright install 

      # Step 4: Run Playwright tests
      - name: Run Playwright tests
        run: npm run test:e2e

      # Step 5: Upload Playwright report as an artifact
      - name: Upload Playwright report
        if: always() # This ensures the report is uploaded even if tests fail
        uses: actions/upload-artifact@v3 # Atualize para v3
        with:
          name: playwright-report
          path: playwright-report # Caminho onde o relatório HTML é gerado
    # Step 7: Deploy Playwright report to GitHub Pages
      - name: Deploy Playwright report to GitHub Pages
        if: success() # Only deploy if tests pass
        uses: peaceiris/actions-gh-pages@v3
        with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./playwright-report